### ISSUE TITLE
GeoIP doesn't build on OSX 10.9

### ISSUE THREAD

**Issue by rickeyski** [maxmind/geoip-api-python#16]
Pip install fails with the following output:

```
building 'GeoIP' extension
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c py_GeoIP.c -o build/temp.macosx-10.9-x86_64-2.7/py_GeoIP.o -fno-strict-aliasing
    py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not found
    #include "GeoIP.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    Complete output from command /mnt/bin/python -c "import setuptools, tokenize;__file__='/mnt/build/GeoIP/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/z5/wdtm1zm57bb99dq2nztfcf2m0000gn/T/pip-Mk_hHx-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/bin/../include/site/python2.7:
```

**Comment by IanZhao** [comment]
Thanks @oschwald, that solved my issue.
Simply did a `brew install libGeoIp`
I'm on OSX 10.11.6

**Comment by matplo** [comment]
brew install geoip
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" pip install GeoIP
